I can't believe I did this
danii/owo-code pull request #5
Opened 2022-01-05 21:25 UTC by Thatcooldevguy

2022-03-08 22:35 UTC, danii commented
Hi, it's been a while, I've finally bought enough salt to fend off the demons that'll come after I merge this, so let's review.

2022-03-08 22:53 UTC, danii requested changes

2022-03-08 22:53 UTC, danii commented on src/lib.rs
> +		wef => ref,whinebecauseyouhurtmelastnightsad
Appears you've made a mistake here.

2022-03-08 22:53 UTC, danii commented on src/lib.rs
> +		boipussy  => as,
Are you absolutely sure this follows [GitHub's guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines#sexually-obscene-content)? I understand this whole project is a joke, but I don't want any of us breaking any rules here.

2022-03-11 19:08 UTC, AlekEagle commented
**YELLING**

2022-10-18 10:20 UTC, WaviestBalloon commented
Yeller -> Yellow

2024-01-24 15:25 UTC, closed without merging

2024-01-24 17:08 UTC, WaviestBalloon commented
Wow.....

2024-01-24 17:27 UTC, SticksDev commented
LMAO..

I did a repo clean ok lol